version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fifth-felony
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PORT: 3002
    volumes:
      - ./src:/app/src
      - ./app:/app/app
    command: npm run dev
    restart: unless-stopped
