version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fifth-felony-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    networks:
      - fifth-felony

networks:
  fifth-felony:
    driver: bridge
